- api/controllers/authController.js
- api/controllers/registerController.js
- api/models/user.js
- api/routes/src/auth.js
- api/routes/src/register.js
- api/routes/src/userRoute.js
- api/server.js
creation of controllers and routes for the user creation and login, with simple authentication and password hashing
> feat(simple auth and routes)

- client/src/components/LandingPage/LandingPage.jsx
- client/src/components/LandingPage/LandingPage.module.css
I added the basic HTML and css from figma in landing page
> landing basic

- client/package-lock.json
- client/src/components/Card/Card.jsx
- client/src/components/LandingPage/LandingPage.jsx
- client/src/components/LandingPage/LandingPage.module.css
Landing page page with material-ui but without css
> Landing page MUI

- api/controllers/auth/authController.js
- api/controllers/auth/logOutController.js
- api/controllers/auth/refreshTokenController.js
- api/controllers/userStatus/createUserStatusController.js
- api/controllers/userStatus/updateUserStatusController.js
- api/controllers/userStatus/userStatusController.js
- api/models/userStatus.js
- api/routes/MainRouter.js
- api/routes/auth/authRoutes.js
- api/routes/auth/logOutRoutes.js
- api/routes/auth/refreshRoutes.js
- api/routes/userStatus/userStatusRouter.js
Groupe controllers for modularization purposes
> userStatus Route & group controllers

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Home/Home.jsx
Bootstrap installed and imported in app.js
> Bootstrap 

- client/src/components/LandingPage/LandingPage.module.css
- client/src/components/Pages/About/About.jsx
- client/src/components/Pages/About/About.module.css
- client/src/components/Pages/NavBarA/NavBarA.jsx
- client/src/components/Pages/NavBarA/NavBarA.module.css
- client/src/components/Pages/NavBarB/NavBarB.jsx
- client/src/components/Pages/NavBarB/NavBarB.module.css
fix boceto de nosotros y fin de NavBar para revisión
> fix boceto de nosotros

- client/src/components/Pages/Login/Login.jsx
> fix login dni

- client/src/App.css
- client/src/components/Footer/Footer.jsx
- client/src/components/Footer/Footer.module.scss
- client/src/components/Footer/Footer2.jsx
- client/src/components/LandingPage/LandingPage.jsx
- client/src/components/LandingPage/LandingPage.module.css
- client/src/components/Pages/About/About.jsx
- client/src/components/Pages/NavBarA/NavBarA.jsx
- client/src/components/Pages/NavBarB/NavBarB.jsx
- client/src/components/Pages/NavBarB/NavBarB.module.css
- client/src/index.css
landing responsive
h1 responsive
h2 responsive
fix class se NavBar para hacerlo transparente
fix  class index , add media querys
> landing responsive

- api/README.md
- api/controllers/courses/readCoursesController.js
- api/controllers/newsLetter/createNewsLetterController.js
- api/controllers/newsLetter/deleteNewsLetterController.js
- api/controllers/user/newUserController.js
- api/routes/courses/coursesRouter.js
Routes documentation and improvements in some controllers
> Added more documentation

- api/controllers/auth/authController.js
- api/controllers/blog/createBlogController.js
- api/controllers/blog/deleteBlogController.js
- api/controllers/blog/getBlogController.js
- api/controllers/blog/updateBlogController.js
- api/middleware/approvedUser.js
- api/models/blogs.js
- api/package-lock.json
- api/package.json
- api/routes/MainRouter.js
- api/routes/blogs/blogsRouter.js
nodeMailer implemented when approved userStatus
> feat(blogControllers&routes)

- .gitignore
- api/README.md
- api/controllers/documents/readDocumentsController.js
- api/controllers/userStatus/createUserStatusController.js
- api/routes/MainRouter.js
- api/routes/documents/documentsRouter.js
- api/routes/userStatus/userStatusRouter.js
> userStatus route now manges Documents

- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/components/CreateNew/CreateNew.jsx
- client/src/components/NewCard/NewCard.jsx
- client/src/components/NewDetails/NewDetails.jsx
- client/src/components/News/News.jsx
Form responsive and validate, new details view, redux actions get by id,
> Form responsive and validate, new details view, redux actions get by id,

- client/src/components/CreateNew/CreateNew.jsx
- client/src/components/CreateNew/CreateNew.module.css
- client/src/components/NewCard/NewCard.jsx
- client/src/components/NewDetails/NewDetails.jsx
- client/src/components/News/News.jsx
order columns in New Details, Create New and Cards(but is not finished XD)
> order columns in New Details, Create New and Cards(but is not finished XD)

- client/package-lock.json
- client/package.json
- client/src/components/BlogCard/BlogCard.jsx
- client/src/components/BlogDetail/BlogDetail.jsx
- client/src/components/NewCard/NewCard.jsx
- client/src/components/NewDetails/NewDetails.jsx
Share to social media in News and Blogs
> Share to social media in News and Blogs

- client/src/components/Pages/Contact/Contact.jsx
- client/src/components/Pages/Login/Login.jsx
- client/src/components/Pages/Login/Login.module.css
- client/src/components/Pages/passwordRecovery/PasswordRecovery.jsx
- client/src/components/Pages/passwordRecovery/PasswordRecovery.module.css
- client/src/components/Pages/passwordReset/PasswordReset.jsx
- client/src/components/Pages/passwordReset/PasswordReset.module.css
improvements in the alert system display and minor changes in functionality.
> style(password recovery & login)

- api/controllers/blog/createBlogController.js
- api/controllers/news/createNews.js
- api/controllers/passwordReset/passwordResetController.js
- api/routes/news/newsRouter.js
- client/src/App.js
- client/src/components/CreateBlog/CreateBlog.jsx
- client/src/components/CreateBlog/CreateBlog.module.css
- client/src/components/CreateNew/CreateNew.jsx
- client/src/components/CreateNew/CreateNew.module.css
- client/src/components/LogoutButton/LogoutButton.jsx
- client/src/components/Pages/Login/Login.jsx
- client/src/components/Pages/NavBarA/NavBarA.jsx
- client/src/components/Pages/NavBarB/NavBarB.jsx
- client/src/components/Pages/NavBarB/NavBarB.module.css
- client/src/components/Pages/passwordRecovery/PasswordRecovery.jsx
- client/src/components/PersistLogin/PersistLogin.js
- client/src/components/PersistLogin/PersistLogin.module.css
- client/src/components/RequireAuth/RequireAuth.js
- client/src/components/Unauthorized/Unauthorized.js
- client/src/components/Unauthorized/Unauthorized.module.css
- client/src/hooks/useLogout.js
implement dropdown for app download in NavBar and logout button
> fine tunnig styles and alerts

- dashboard/src/components/pages/Profile/Profile.jsx
> Order Profile responsive

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/Redux/Actions/index.js
- dashboard/src/Redux/Reducer/index.js
- dashboard/src/Redux/Store/index.js
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.js
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.jsx
- dashboard/src/index.js
> DashBoard: Manage Blogs info

- client/src/components/Blog/Blog.jsx
- dashboard/src/App.js
- dashboard/src/Redux/Reducer/index.js
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.jsx
- dashboard/src/components/pages/ManageBlogsById/ManageBlogsById.jsx
> DashBoard: Manage Blogs By Id

- dashboard/src/App.js
- dashboard/src/components/pages/ManageBlogsById/ManageBlogsById.jsx
- dashboard/src/components/pages/ManageNews/ManageNews.js
- dashboard/src/components/pages/ManageNews/ManageNews.jsx
- dashboard/src/components/pages/ManageNewsById/ManageNewsById.jsx
> DashBoard: Manage NewsBy Id

- dashboard/src/Redux/Actions/index.js
- dashboard/src/Redux/Reducer/index.js
- dashboard/src/components/pages/ManageNews/ManageNews.jsx
- dashboard/src/components/pages/PaginationNewsBlogs/PaginationNewsBlogs.jsx
Pagination Dash Board, news and Blogs, useEffect with lag 999
> Pagination Dash Board, news and Blogs, useEffect with lag 999

- client/src/components/Footerx/Footerx.jsx
- client/src/components/FormVolunteer/VolunteerForm.jsx
- Se implementó la validación de show Alert cuando se envía el formulario de voluntarios.
- Se corrigió la Validación de no Ñ ni caracteres especiales en nombres.
- refactorización de varias para las distintas expresiones regulares
> Implementación de ShowAlert en form volunteer

- client/src/components/News/News.jsx
- dashboard/src/components/pages/ManageNews/ManageNews.jsx
Pagination Dash Board, news and tables functional 100%
> Pagination Dash Board, news and tables functional 100%

- api/controllers/documents/readDocumentsController.js
- api/controllers/user/newUserController.js
- api/controllers/userStatus/createUserStatusController.js
- api/routes/user/userRouter.js
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/App.js
- dashboard/src/components/NavBar/SidebarData.js
- dashboard/src/components/pages/CreateNewUser/CreateNewUser.js
- dashboard/src/components/pages/CreateNewUser/CreateNewUser.module.css
Also added credentials to the axios
> Addes BackEnd proteccion to user Route 

- api/controllers/news/updateNews.js
- api/routes/news/newsRouter.js
Saludos y besos ya saben donde
> Update News with cloudinary to img option

- dashboard/src/components/pages/ConfirmationModal/ConfirmationModal.jsx
- dashboard/src/components/pages/ConfirmationModal/ConfirmationModal.module.css
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.jsx
- dashboard/src/components/pages/ManageNews/ManageNews.jsx
Delete Blog and Delete New in dashboard with modal from JuanPa
> Delete Blog and Delete New in dashboard with modal from JuanPa

- client/src/components/Pages/Contact/Contact.jsx
- dashboard/src/App.js
- dashboard/src/components/Footer/Footer.jsx
- dashboard/src/components/Footer/Footer.module.css
- dashboard/src/components/NavBar/Navbar.css
- dashboard/src/components/NavBar/Navbar.js
- dashboard/src/components/RemoveUserButton/RemoveUserButton.js
- dashboard/src/components/pages/Bienvenidos/Bienvenidos.module.css
- dashboard/src/components/pages/DeleteUser/DeleteUser.js
- dashboard/src/components/pages/ManageVolunteers/ManageVolunteers.jsx
cursor to and fix Navbar Menu, standard Footer, confirmation delete user
> fixes(various correction)

- dashboard/src/App.css
- dashboard/src/App.js
- dashboard/src/components/CreateBlog/CreateBlog.module.css
- dashboard/src/components/CreateNew/CreateNew.module.css
- dashboard/src/components/Footer/Footer.jsx
- dashboard/src/components/Footer/Footer.module.css
- dashboard/src/components/NavBar/Navbar.css
- dashboard/src/components/Students/Students/Students.jsx
- dashboard/src/components/Students/Students/Students.module.css
- dashboard/src/components/Students/StudentsPlayer/StudentsPlayer.jsx
- dashboard/src/components/Students/StudentsPlayer/studentsPlayer.css
- dashboard/src/components/pages/Bienvenidos/Bienvenidos.module.css
- dashboard/src/components/pages/CreateNewUser/CreateNewUser.js
- dashboard/src/components/pages/CreateNewUser/CreateNewUser.module.css
- dashboard/src/components/pages/DeleteUser/DeleteUser.js
- dashboard/src/components/pages/DeleteUser/DeleteUser.module.css
- dashboard/src/components/pages/Login/Login.module.css
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.jsx
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.module.css
- dashboard/src/components/pages/ManageBlogsById/ManageBlogsById.jsx
- dashboard/src/components/pages/ManageBlogsById/ManageBlogsById.module.css
- dashboard/src/components/pages/ManageNews/ManageNews.jsx
- dashboard/src/components/pages/ManageNews/ManageNews.module.css
- dashboard/src/components/pages/ManageNewsById/ManageNewsById.jsx
- dashboard/src/components/pages/ManageNewsById/ManageNewsById.module.css
- dashboard/src/components/pages/ManageVolunteers/ManageVolunteers.module.css
- dashboard/src/components/pages/Sustcriptors/Suscriptors.js
- dashboard/src/components/pages/Sustcriptors/Suscriptors.module.css
improve the navbar implementaion plus the footer and minor corrections
> improvementes in styles implementation DashBoard

- api/controllers/auth/refreshTokenController.js
- api/controllers/user/newUserController.js
- api/controllers/user/readUserController.js
- api/controllers/user/readUserIdController.js
- api/controllers/user/updateUserInfoController.js
- api/controllers/userStatus/getEditInfo.js
- api/controllers/userStatus/upadateUserStatusInfoController.js
- api/routes/user/userRouter.js
- api/routes/userStatus/userStatusRouter.js
- dashboard/src/components/pages/Profile/Profile.jsx
also added routes in back to support this funcionality
> Added update user info view

- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/components/Blog/Blog.jsx
- client/src/components/NewCard/NewCard.jsx
- client/src/components/News/News.jsx
- client/src/components/Pages/FilterCategory/FilterCategory.jsx
- client/src/components/Pages/SeachBar/SearchBar.jsx
- client/src/components/Pages/SortByDate/SortByDate.jsx
- dashboard/src/Redux/Actions/index.js
- dashboard/src/Redux/Reducer/index.js
- dashboard/src/components/CreateNew/CreateNew.jsx
Pagination with search by name and title functional in client
> Pagination with search by name and title functional in client

- client/src/components/FormVolunteer/FormVolunteer.module.css
- client/src/components/FormVolunteer/VolunteerForm.jsx
- client/src/components/Pages/Contact/Contact.module.css
- dashboard/src/components/Students/CreateCourse/CreateCourse.jsx
- Form Volunteer h1 y h2
- Button contact us
> Fix styles

- client/src/components/BlogCard/BlogCard.jsx
- client/src/components/NewCard/NewCard.jsx
News and Blogs with out social media repeat
> News and Blogs with out social media repeat

- api/controllers/news/createNews.js
- api/controllers/userStatus/createUserStatusController.js
> Fix the news Creation

- client/src/components/Pages/NavBarA/NavBarA.jsx
> fix noticias navBar A

- client/src/components/NewsLetterB/NewsLetterB.module.css
override the default bootstrap settings on the modal
> fix(newsLetterModal styles

- dashboard/src/components/NavBar/Navbar.js
- dashboard/src/components/pages/ManageBlogs/ManageBlogs.jsx
- dashboard/src/components/pages/ManageNews/ManageNews.jsx
- dashboard/src/components/pages/ManageNews/ManageNews.module.css
- dashboard/src/components/pages/PaginationNewsBlogs/PaginationNewsBlogs.jsx
adding image picture and better date format
> fix(improve styles in manageNews

- client/public/_redirects
- client/public/netlify.toml
> Fix navegacion netlify

- client/public/netlify.toml
> fix navegación netlify plus

- api/controllers/blog/getBlogController.js
- dashboard/src/App.js
- dashboard/src/Redux/Actions/index.js
- dashboard/src/Redux/Reducer/index.js
- dashboard/src/components/NavBar/Navbar.css
- dashboard/src/components/NavBar/Navbar.js
- dashboard/src/components/NavBar/SidebarData.js
- dashboard/src/components/pages/MyBlogs/MyBlogs.jsx
- dashboard/src/components/pages/MyBlogs/MyBlogs.module.css
implement MyBlogs view and making blogs panel only for admin
> feat(Myblogs & fixes to blogs panel
